name: Robot Framework CI

on:
  push:
    branches:
      - main
  # pull_request:
  #   branches:
  #     - main

jobs:
  robot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x" # Substitua pela versão do Python que você deseja usar

      # - name: Install Node.js
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: "14" # Substitua pela versão do Node.js que você deseja usar

      # - name: Install Node.js dependencies
      #   run: |
      #     npm install

      # - name: Install Python dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install robotframework

      # - name: Run Robot Framework tests
      #   run: |
      #     robot --outputdir results path/to/your/tests

      # - name: Archive test results
      #   if: always()
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: robot-results
      #     path: results
