name: Robot Framework CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env: 
  token: ${{ secrets.BEARER_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]

    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: https://FelipeLoureiroQA.github.io/robot-framework-api-spotify/reports/report.html

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install robotframework
          pip install robotframework-requests
          pip install python-dotenv
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Use secret
        run: echo "My secret is ${{ secrets.BEARER_TOKEN }}"
      - name: Run Robot Framework tests
        run: |
          robot -d ./reports tests

      - name: Deploy no GitHub Pages
        uses: actions/upload-artifact@v4.3.4
        if: always()
        with:
          name: reports
          path: ./reports
