name: Robot Framework CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x" # Você pode especificar a versão do Python que precisa

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install robotframework
          pip install robotframework-requests

      - name: Run Robot Framework tests
        run: |
          robot --outputdir results tests/

      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: robotframework-results
          path: results/
