name: Robot Framework CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env: 
  token: ${{ secrets.BEARER_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]

    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: https://felipeloureiroqa.github.io/robot-framework-report-api/report.html

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install robotframework
          pip install robotframework-requests
          pip install python-dotenv
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run Robot Framework Tests
        run: |
          robot -d ./tests/reports tests

      - name: Setup Pages
        uses: actions/configure-pages@v4

      # - name: Download Artifacts
      #   uses: actions/download-artifact@v4
      #   with: 
      #     name: robot-framework-report
      #     path: ./tests/reports

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./reports


      - name: Deploy no GitHub Pages
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: reports
          path: ./tests/reports
