
name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - run: npm ci
      - run: npm run prettier-check
      - run: npm test
# name: Pipeline Test

# on: push

# jobs:
#   test:
#     name: Testes de API
#     runs-on: ubuntu-latest

#     permissions:
#       contents: read
#       pages: write
#       id-token: write
#     environment:
#       name: github-pages
#       url: https://FelipeLoureiroQA.github.io/robot-framework-api-spotify/report.html

    # steps:
    #   - name: Clonagem Projeto
    #     uses: actions/checkout@v3

    #   - name: Configuração do Python
    #     uses: actions/setup-python@v2
    #     with:
    #       python-version: "3.12"

    #   - name: Instalar Dependencias do Projeto
    #     run: |
    #       pip install robotframework
    #       pip install robotframework-requests

    #   - name: Execução dos Testes de API
    #     run: |
    #       robot --outputdir results/ tests/

    #   - name: Salvando Resultado dos Testes
    #     uses: actions/upload-artifact@v4
    #     if: always()
    #     with:
    #       name: resultado-testes
    #       path: /results

    #   - name: Configurar Site de Relatorios dos Testes
    #     uses: actions/configure-pages@v5
    #     if: always()

    #   - name: Upload artifact
    #     uses: actions/upload-pages-artifact@v3
    #     if: always()
    #     with:
    #       path: results/

    #   - name: Relatorios dos Testes
    #     id: deployment
    #     uses: actions/deploy-pages@v4
    #     if: always()
