name: Robot Framework CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env: 
  token: ${{ secrets.BEARER_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]

    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: https://FelipeLoureiroQA.github.io/test/report.html

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install robotframework
          pip install robotframework-requests
          pip install python-dotenv
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Use secret
        run: echo "My secret is ${{ secrets.BEARER_TOKEN }}"
      - name: Run Robot Framework tests
        run: |
          robot -d results tests
          # robot --outputdir results tests/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site